export const credits = [
  { name: "Janus Engine", job: "The" },
  { name: "Joel Robinson", job: "Director" },
  { name: "Joel Robinson", job: "Executive Producer" },
  { name: "Joel Robinson", job: "Writer" },
  { name: "Joel Robinson", job: "Asset Design" },
  { name: "Joel Robinson", job: "Editor" },
  { name: "Joel Robinson", job: "Catering" },
  { name: "James Carter", job: "Moral Support" },
  { name: "Saul Ashbridge", job: "Friendly Rival" },
  { name: "Jake Hobbs", job: "Very Nice People" },
  { name: "Matt Thompson", job: "Very Nice People" },
  { name: "Hadrian", job: "Additonal Assets" },
  { name: "Google (Sue Me)", job: "Background Images" },
  { name: "Mrthenoronha", job: "Main Theme by" },
  { name: "alaupas", job: "Additional Music by" },
  { name: "Rick Astley", job: "Special Thanks to" },
  { name: "", job: "" },
  { name: "", job: "" },
  { name: "", job: "" },
  { name: "Why are you still here?", job: "Hey!" },
  { name: "Marvel movie", job: "This isn't a friggin'" },
  { name: "dude", job: "Whatever" },
  { name: "sweet, sweet Astley", job: "There's still a full minute of" },
];
